name: SouthPlus签到

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set locale to UTF-8
      run: |
        sudo apt-get update
        sudo apt-get install -y locales
        sudo locale-gen en_US.UTF-8
        sudo update-locale LANG=en_US.UTF-8
      env:
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8

    - name: Run main script
      env:
        COOKIE: ${{ secrets.COOKIE }}
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
      run: python main.py
